[package]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
name = "rust-no-std-tutorial"
edition = "2024"
version = "0.1.0"

[lints.rust]
warnings = "warn"
dead-code = "warn"

[lints.clippy]
needless_return = "allow"
implicit_return = "forbid"
pedantic = { level = "deny", priority = -1 }
print_stdout = "allow"
trivially_copy_pass_by_ref = "allow"

[[bin]]
name = "main"
test = false

[lib]
harness = false

# needed for each integration test
[[test]]
name = "integration"
harness = false

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
defmt = "1.0"
defmt-semihosting = "0.3.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
semihosting = "0.1.20"

[dev-dependencies]
defmt-test = "0.3"
